<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/Missing_Value_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DETECTING MISSING VALUES**

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv(r"/content/Diabetes Missing Data.csv")

1.BASIC IMPLEMENTATION

In [7]:
df.isnull()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,True,True,False,False,False,False
767,False,False,False,False,True,False,False,False,False

2.NUMBER OF NULL VALUES

In [8]:
df.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

3.TOTAL NUMBER OF NULL VALUES

In [10]:
print(df.isnull().sum().sum())

652

4.ROWS WITH ATLEAST ONE NULL VALUES

In [21]:
df[df.isnull().any(axis=1)].head(10)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1
10,4,110.0,92.0,NaN,NaN,37.6,0.191,30,0
11,10,168.0,74.0,NaN,NaN,38.0,0.537,34,1
12,10,139.0,80.0,NaN,NaN,27.1,1.441,57,0
15,7,100.0,NaN,NaN,NaN,30.0,0.484,32,1

5.ROWS WITH NULL VALUES IN ALL FIELDS

In [19]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [Pregnant, Glucose, Diastolic_BP, Skin_Fold, Serum_Insulin, BMI, Diabetes_Pedigree, Age, Class]
Index: []

6.COLUMN NAMES WITH NULL VALUES

In [24]:
df.columns[df.isnull().any()]

Index(['Glucose', 'Diastolic_BP', 'Skin_Fold', 'Serum_Insulin', 'BMI'], dtype='object')

7.TO FIND WHETHER NULL VALUES PRESENT

In [25]:
df.isnull().values.any()

np.True_

8.PERCENTAGE OF NULL VALUES

In [28]:
(df.isnull().sum()/len(df))*100

Pregnant              0.000000
Glucose               0.651042
Diastolic_BP          4.557292
Skin_Fold            29.557292
Serum_Insulin        48.697917
BMI                   1.432292
Diabetes_Pedigree     0.000000
Age                   0.000000
Class                 0.000000
dtype: float64

9.FILTERING MISSING ROWS IN ONE COLUMN

In [31]:
df['Diabetes_Pedigree'].isnull().head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Diabetes_Pedigree, dtype: bool

10.FILTERING MISSING VALUES IN MULTIPLE COLUMNS

In [33]:
df[['Diastolic_BP','Diabetes_Pedigree']].isnull().head(10)

   Diastolic_BP  Diabetes_Pedigree
0         False              False
1         False              False
2         False              False
3         False              False
4         False              False
5         False              False
6         False              False
7          True              False
8         False              False
9         False              False

11.NOT NULL IMPLEMENTATION

In [13]:
df.notnull()

Pregnant             768
Glucose              763
Diastolic_BP         733
Skin_Fold            541
Serum_Insulin        394
BMI                  757
Diabetes_Pedigree    768
Age                  768
Class                768
dtype: int64

12.TOTAL SUM OF NOT NULL VALUES

In [16]:
print(df.notnull().sum().sum())

6260

13.TO CHECK WHETHER ALL VALUES ARE NULL VALUES

In [29]:
df.notnull().all().all()

np.False_