<a href="https://colab.research.google.com/github/belindacarolam04/pandas_learning/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SORTING**

In [1]:
import pandas as pd

In [2]:
import kagglehub

path = kagglehub.dataset_download(
    "shivasingh4945/enhanced-breast-cancer-diagnostic-dataset"
)

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/1.archive...

100%|██████████| 812k/812k [00:00<00:00, 66.8MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/shivasingh4945/enhanced-breast-cancer-diagnostic-dataset/versions/1

In [3]:
import os

print(os.listdir(path))

['breast_cancer_enhanced_dataset.csv']

In [5]:
df=pd.read_csv(f"{path}/breast_cancer_enhanced_dataset.csv")

1.SORT BASED ON ONE COLUMN

In [7]:
df.sort_values('radius_mean').head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
3878,5.251194e+06,B,6.817646,13.723817,44.806926,153.821111,0.117817,0.075050,-0.001573,-0.000842,0.072635,1.324025e-06,0.024212,93.564134,-0.010725,-0.000010,12.845774
1701,6.852563e+06,B,6.901812,13.519074,44.215425,149.287899,0.117382,0.077558,0.000614,-0.000187,0.077985,-1.149870e-07,0.025995,93.306108,0.004235,0.000004,12.789963
1173,3.541090e+06,B,6.920874,13.415905,42.639188,130.077886,0.116835,0.076675,-0.002484,0.001708,0.075899,-4.242990e-06,0.025300,92.849788,-0.017189,-0.000019,12.370635
5390,3.177355e+06,B,6.920896,13.429173,43.921917,161.963381,0.115928,0.076207,-0.001065,0.000260,0.075402,-2.771910e-07,0.025134,92.941914,-0.007373,-0.000007,12.690576
4225,8.882197e+06,B,6.974476,13.399029,42.768031,123.928240,0.117668,0.074557,0.001423,-0.000032,0.075947,-4.558807e-08,0.025316,93.451207,0.009923,0.000011,12.470395
3823,-1.713684e+06,B,7.012162,13.580969,43.059031,126.511189,0.116381,0.075656,0.001440,0.000825,0.077921,1.187454e-06,0.025974,95.231963,0.010097,0.000011,12.574413
1882,4.779613e+05,B,7.060189,13.508278,44.875726,144.765311,0.117093,0.076820,0.001853,0.001199,0.079872,2.221574e-06,0.026624,95.370989,0.013082,0.000013,13.060275
2274,1.817457e+06,B,7.090985,13.478545,44.537156,154.960980,0.117022,0.072852,0.001081,-0.000402,0.073530,-4.348567e-07,0.024510,95.576156,0.007663,0.000007,12.923991
3440,5.744646e+06,B,7.568731,25.532741,48.172018,154.523808,0.086815,0.116829,0.094047,0.014134,0.225010,1.329283e-03,0.075003,193.250452,0.711819,0.000609,16.639725
4686,1.525327e+05,B,7.569561,25.358948,47.816045,176.026446,0.087172,0.120530,0.091092,0.011696,0.223318,1.065393e-03,0.074439,191.956106,0.689527,0.000517,16.416097

2.SORT BASED ON MULTIPLE COLUMNS

In [9]:
df.sort_values(['radius_mean','texture_mean']).head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
3878,5.251194e+06,B,6.817646,13.723817,44.806926,153.821111,0.117817,0.075050,-0.001573,-0.000842,0.072635,1.324025e-06,0.024212,93.564134,-0.010725,-0.000010,12.845774
1701,6.852563e+06,B,6.901812,13.519074,44.215425,149.287899,0.117382,0.077558,0.000614,-0.000187,0.077985,-1.149870e-07,0.025995,93.306108,0.004235,0.000004,12.789963
1173,3.541090e+06,B,6.920874,13.415905,42.639188,130.077886,0.116835,0.076675,-0.002484,0.001708,0.075899,-4.242990e-06,0.025300,92.849788,-0.017189,-0.000019,12.370635
5390,3.177355e+06,B,6.920896,13.429173,43.921917,161.963381,0.115928,0.076207,-0.001065,0.000260,0.075402,-2.771910e-07,0.025134,92.941914,-0.007373,-0.000007,12.690576
4225,8.882197e+06,B,6.974476,13.399029,42.768031,123.928240,0.117668,0.074557,0.001423,-0.000032,0.075947,-4.558807e-08,0.025316,93.451207,0.009923,0.000011,12.470395
3823,-1.713684e+06,B,7.012162,13.580969,43.059031,126.511189,0.116381,0.075656,0.001440,0.000825,0.077921,1.187454e-06,0.025974,95.231963,0.010097,0.000011,12.574413
1882,4.779613e+05,B,7.060189,13.508278,44.875726,144.765311,0.117093,0.076820,0.001853,0.001199,0.079872,2.221574e-06,0.026624,95.370989,0.013082,0.000013,13.060275
2274,1.817457e+06,B,7.090985,13.478545,44.537156,154.960980,0.117022,0.072852,0.001081,-0.000402,0.073530,-4.348567e-07,0.024510,95.576156,0.007663,0.000007,12.923991
3440,5.744646e+06,B,7.568731,25.532741,48.172018,154.523808,0.086815,0.116829,0.094047,0.014134,0.225010,1.329283e-03,0.075003,193.250452,0.711819,0.000609,16.639725
4686,1.525327e+05,B,7.569561,25.358948,47.816045,176.026446,0.087172,0.120530,0.091092,0.011696,0.223318,1.065393e-03,0.074439,191.956106,0.689527,0.000517,16.416097

3.SORTING MULTIPLE COLUMNS IN DIFFERENT ORDER

In [10]:
df.sort_values(['radius_mean','texture_mean'],ascending=[True,False]).head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
3878,5.251194e+06,B,6.817646,13.723817,44.806926,153.821111,0.117817,0.075050,-0.001573,-0.000842,0.072635,1.324025e-06,0.024212,93.564134,-0.010725,-0.000010,12.845774
1701,6.852563e+06,B,6.901812,13.519074,44.215425,149.287899,0.117382,0.077558,0.000614,-0.000187,0.077985,-1.149870e-07,0.025995,93.306108,0.004235,0.000004,12.789963
1173,3.541090e+06,B,6.920874,13.415905,42.639188,130.077886,0.116835,0.076675,-0.002484,0.001708,0.075899,-4.242990e-06,0.025300,92.849788,-0.017189,-0.000019,12.370635
5390,3.177355e+06,B,6.920896,13.429173,43.921917,161.963381,0.115928,0.076207,-0.001065,0.000260,0.075402,-2.771910e-07,0.025134,92.941914,-0.007373,-0.000007,12.690576
4225,8.882197e+06,B,6.974476,13.399029,42.768031,123.928240,0.117668,0.074557,0.001423,-0.000032,0.075947,-4.558807e-08,0.025316,93.451207,0.009923,0.000011,12.470395
3823,-1.713684e+06,B,7.012162,13.580969,43.059031,126.511189,0.116381,0.075656,0.001440,0.000825,0.077921,1.187454e-06,0.025974,95.231963,0.010097,0.000011,12.574413
1882,4.779613e+05,B,7.060189,13.508278,44.875726,144.765311,0.117093,0.076820,0.001853,0.001199,0.079872,2.221574e-06,0.026624,95.370989,0.013082,0.000013,13.060275
2274,1.817457e+06,B,7.090985,13.478545,44.537156,154.960980,0.117022,0.072852,0.001081,-0.000402,0.073530,-4.348567e-07,0.024510,95.576156,0.007663,0.000007,12.923991
3440,5.744646e+06,B,7.568731,25.532741,48.172018,154.523808,0.086815,0.116829,0.094047,0.014134,0.225010,1.329283e-03,0.075003,193.250452,0.711819,0.000609,16.639725
4686,1.525327e+05,B,7.569561,25.358948,47.816045,176.026446,0.087172,0.120530,0.091092,0.011696,0.223318,1.065393e-03,0.074439,191.956106,0.689527,0.000517,16.416097

4.SORTING BASED ON INDEX

In [12]:
df.sort_index().head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
0,5.683796e+06,B,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,0.000185,0.026075,257.017451,0.187718,0.000036,22.433798
1,-6.253379e+06,B,10.991150,17.103260,71.798929,381.386295,0.089339,0.109498,0.097344,0.035629,0.242470,0.003468,0.080823,187.984489,1.069921,0.000255,24.021839
2,4.213892e+06,M,21.433519,15.092437,142.753006,1392.399890,0.099557,0.152079,0.193372,0.126922,0.472373,0.024543,0.157458,323.484034,4.144647,0.000139,49.053992
3,-2.986069e+06,B,11.700452,14.872127,74.154481,404.112556,0.101291,0.077563,0.043749,0.028747,0.150059,0.001258,0.050020,174.010599,0.511885,0.000108,23.276145
4,6.469594e+05,B,13.259377,17.212990,83.621014,521.124238,0.072905,0.043312,0.046983,0.010096,0.100391,0.000474,0.033464,228.233523,0.622960,0.000090,25.647074
5,-4.581518e+05,B,11.620937,16.155888,76.026791,436.142831,0.112669,0.095446,0.036704,0.031314,0.163464,0.001149,0.054488,187.746558,0.426530,0.000084,23.612382
6,6.104780e+06,B,12.166927,14.868031,78.601322,428.659208,0.103159,0.090379,0.066778,0.027997,0.185154,0.001870,0.061718,180.898245,0.812485,0.000156,25.061439
7,9.398100e+07,B,13.443279,18.669093,87.810591,564.287299,0.106001,0.115531,0.083967,0.054183,0.253681,0.004550,0.084560,250.973833,1.128795,0.000149,28.767221
8,2.722075e+06,B,8.743292,15.826895,54.991483,253.178665,0.114348,0.080234,0.040824,0.019867,0.140925,0.000811,0.046975,138.379160,0.356940,0.000161,17.450987
9,1.403596e+06,M,18.083293,18.692756,120.690753,1034.577981,0.115221,0.150960,0.177470,0.105356,0.433786,0.018698,0.144595,338.026597,3.209245,0.000172,41.764167

5.DESCENDING ORDER

In [13]:
df.sort_index(ascending=False).head(10) #descending

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
5499,-3.163711e+06,M,19.936731,22.043719,129.216656,1269.726727,0.098140,0.102896,0.146180,0.096857,0.345933,0.014159,0.115311,439.479696,2.914349,0.000115,43.364274
5498,7.519916e+06,M,20.946319,25.233666,142.498720,1340.103257,0.109454,0.226277,0.316075,0.148336,0.690688,0.046885,0.230229,528.552405,6.620608,0.000236,52.471548
5497,-4.461865e+06,M,19.403923,18.152520,127.631265,1129.627896,0.104142,0.144262,0.164108,0.094511,0.402881,0.015510,0.134294,352.230108,3.184337,0.000145,43.224263
5496,4.399236e+05,B,13.831066,19.454900,88.204429,580.072530,0.087240,0.061584,0.012322,0.022518,0.096424,0.000277,0.032141,269.082007,0.170427,0.000021,26.379882
5495,2.909607e+06,B,11.688492,18.217548,75.277156,429.895271,0.113777,0.104274,0.069515,0.034620,0.208409,0.002407,0.069470,212.935657,0.812528,0.000162,24.344788
5494,2.477849e+06,B,10.791094,17.207447,71.872111,370.878589,0.088964,0.110048,0.097307,0.037295,0.244650,0.003629,0.081550,185.687173,1.050053,0.000262,24.030855
5493,-5.187229e+06,M,14.948190,16.846998,98.779466,658.925449,0.116212,0.164118,0.170060,0.090065,0.424243,0.015317,0.141414,251.832128,2.542095,0.000258,34.935053
5492,1.733785e+06,M,13.736838,24.919536,88.238364,579.112750,0.095047,0.086599,0.085256,0.045838,0.217692,0.003908,0.072564,342.315635,1.171146,0.000147,28.771136
5491,1.599844e+07,B,11.972502,24.934269,76.618332,430.183742,0.102860,0.094415,0.055275,0.042504,0.192194,0.002349,0.064065,298.525577,0.661777,0.000128,24.592183
5490,8.177530e+06,B,10.720594,20.395350,69.557507,346.798775,0.108093,0.131209,0.084799,0.026587,0.242595,0.002255,0.080865,218.650272,0.909092,0.000245,22.854174

7.SORTING IN ALPHABETICAL ORDER

In [14]:
df.sort_values('diagnosis').head(10) #arranges in alphabetical order

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
0,5.683796e+06,B,11.829858,21.726166,75.154378,435.022394,0.087089,0.050717,0.015868,0.011641,0.078226,1.847278e-04,0.026075,257.017451,0.187718,0.000036,22.433798
3247,-3.498287e+06,B,11.892070,21.651870,75.089078,445.011267,0.086003,0.048253,0.018836,0.010434,0.077523,1.965396e-04,0.025841,257.485560,0.224003,0.000042,22.477047
3248,4.404343e+06,B,12.913666,18.012246,83.112003,500.775043,0.098852,0.098827,0.038089,0.021025,0.157941,8.008316e-04,0.052647,232.604117,0.491871,0.000076,25.484276
3249,1.167901e+07,B,13.256520,17.222442,84.127378,548.288443,0.084260,0.047350,0.034822,0.024141,0.106313,8.406313e-04,0.035438,228.309646,0.461616,0.000064,25.820043
3250,1.795332e+06,B,9.803274,18.274525,60.869439,282.960844,0.069339,0.026369,-0.000673,-0.000597,0.025100,4.016275e-07,0.008367,179.150163,-0.006593,-0.000002,17.636435
3251,3.199224e+06,B,10.113949,21.616253,62.521401,313.889449,0.080831,0.039067,0.005039,0.002089,0.046195,1.052586e-05,0.015398,218.625683,0.050969,0.000016,18.337041
3252,-6.038245e+06,B,12.409891,21.806432,80.194899,461.016302,0.088248,0.094081,0.058830,0.037659,0.190570,2.215469e-03,0.063523,270.615449,0.730077,0.000128,25.563421
3253,3.246237e+06,B,11.597655,19.063730,75.301905,423.556841,0.088387,0.068987,0.028113,0.014650,0.111750,4.118445e-04,0.037250,221.094550,0.326047,0.000066,22.793957
3255,-9.558457e+06,B,12.506330,18.720745,79.170391,461.400698,0.084270,0.070529,0.027219,0.017431,0.115179,4.744550e-04,0.038393,234.127813,0.340414,0.000059,24.035434
3256,5.455601e+06,B,11.467220,12.749125,75.507478,423.915601,0.089289,0.074154,0.044119,0.034973,0.153245,1.542962e-03,0.051082,146.197021,0.505921,0.000104,23.720967

8.SORT BASED ON COLUMN NAMES

In [16]:
df.sort_index(axis=1) #arranges the columns in alphabetical order

,area_mean,border_complexity,compactness_mean,concave points_mean,concavity_density,concavity_mean,diagnosis,id,malignancy_risk_score,perimeter_mean,radius_concavity_interaction,radius_mean,radius_texture_interaction,shape_irregularity,smoothness_mean,texture_mean,tumor_aggressiveness
0,435.022394,0.000185,0.050717,0.011641,0.000036,0.015868,B,5.683796e+06,22.433798,75.154378,0.187718,11.829858,257.017451,0.078226,0.087089,21.726166,0.026075
1,381.386295,0.003468,0.109498,0.035629,0.000255,0.097344,B,-6.253379e+06,24.021839,71.798929,1.069921,10.991150,187.984489,0.242470,0.089339,17.103260,0.080823
2,1392.399890,0.024543,0.152079,0.126922,0.000139,0.193372,M,4.213892e+06,49.053992,142.753006,4.144647,21.433519,323.484034,0.472373,0.099557,15.092437,0.157458
3,404.112556,0.001258,0.077563,0.028747,0.000108,0.043749,B,-2.986069e+06,23.276145,74.154481,0.511885,11.700452,174.010599,0.150059,0.101291,14.872127,0.050020
4,521.124238,0.000474,0.043312,0.010096,0.000090,0.046983,B,6.469594e+05,25.647074,83.621014,0.622960,13.259377,228.233523,0.100391,0.072905,17.212990,0.033464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,429.895271,0.002407,0.104274,0.034620,0.000162,0.069515,B,2.909607e+06,24.344788,75.277156,0.812528,11.688492,212.935657,0.208409,0.113777,18.217548,0.069470
5496,580.072530,0.000277,0.061584,0.022518,0.000021,0.012322,B,4.399236e+05,26.379882,88.204429,0.170427,13.831066,269.082007,0.096424,0.087240,19.454900,0.032141
5497,1129.627896,0.015510,0.144262,0.094511,0.000145,0.164108,M,-4.461865e+06,43.224263,127.631265,3.184337,19.403923,352.230108,0.402881,0.104142,18.152520,0.134294
5498,1340.103257,0.046885,0.226277,0.148336,0.000236,0.316075,M,7.519916e+06,52.471548,142.498720,6.620608,20.946319,528.552405,0.690688,0.109454,25.233666,0.230229
5499,1269.726727,0.014159,0.102896,0.096857,0.000115,0.146180,M,-3.163711e+06,43.364274,129.216656,2.914349,19.936731,439.479696,0.345933,0.098140,22.043719,0.115311

9.N LARGEST

In [17]:
df.nlargest(8,'area_mean')

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,shape_irregularity,border_complexity,tumor_aggressiveness,radius_texture_interaction,radius_concavity_interaction,concavity_density,malignancy_risk_score
575,1.485636e+07,M,28.037554,18.505108,187.798686,2507.982355,0.115066,0.151185,0.319866,0.157963,0.629014,0.050527,0.209671,518.837982,8.968264,0.000128,65.904800
497,3.680075e+06,M,28.134575,18.675329,188.730042,2507.933865,0.113976,0.151470,0.319505,0.160258,0.631233,0.051203,0.210411,525.422450,8.989126,0.000127,66.210220
2653,9.562581e+06,M,28.085196,18.434952,188.552674,2507.574607,0.114925,0.153464,0.321570,0.160146,0.635180,0.051498,0.211727,517.749251,9.031344,0.000128,66.202363
3867,9.115380e+08,M,27.426697,26.285319,186.236848,2507.547634,0.108528,0.200872,0.362085,0.167675,0.730632,0.060712,0.243544,720.919460,9.930793,0.000144,66.659875
4039,8.009618e+06,M,28.067674,18.477850,188.983008,2501.568981,0.114228,0.153200,0.324914,0.160105,0.638219,0.052020,0.212740,518.630280,9.119588,0.000130,66.388146
1267,1.298915e+06,M,28.180977,18.450093,188.271693,2499.413980,0.114077,0.153222,0.323629,0.159020,0.635870,0.051463,0.211957,519.941649,9.120178,0.000129,66.179382
2683,9.124480e+08,M,27.281185,26.371081,187.065254,2498.834947,0.108807,0.199534,0.361254,0.169898,0.730685,0.061376,0.243562,719.434333,9.855425,0.000145,66.865392
373,9.557969e+06,M,28.226659,18.475831,188.331034,2496.606181,0.114306,0.151275,0.322009,0.158492,0.631776,0.051036,0.210592,521.510983,9.089236,0.000129,66.151952

10.N SMALLEST

In [22]:
df.nsmallest(8,'area_mean')[['id','area_mean']]

                id   area_mean
4225  8.882197e+06  123.928240
3823 -1.713684e+06  126.511189
1173  3.541090e+06  130.077886
1882  4.779613e+05  144.765311
1701  6.852563e+06  149.287899
3878  5.251194e+06  153.821111
3440  5.744646e+06  154.523808
2274  1.817457e+06  154.960980